// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqPMZnyMUd0_5QsOFwERE6fGixhXfQDRs',
    appId: '1:927459952659:web:35872d17d50cc12759d7e6',
    messagingSenderId: '927459952659',
    projectId: 'flutterchatapp-c21a5',
    authDomain: 'flutterchatapp-c21a5.firebaseapp.com',
    storageBucket: 'flutterchatapp-c21a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChlJPfaYiYoXNNfCYcCnsUaH4rasLDNP8',
    appId: '1:927459952659:android:7291459f59a43f5059d7e6',
    messagingSenderId: '927459952659',
    projectId: 'flutterchatapp-c21a5',
    storageBucket: 'flutterchatapp-c21a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2ahL87wv2e8sjTC-K6tKgg96urXCeWvM',
    appId: '1:927459952659:ios:f578a039f3472b3e59d7e6',
    messagingSenderId: '927459952659',
    projectId: 'flutterchatapp-c21a5',
    storageBucket: 'flutterchatapp-c21a5.appspot.com',
    iosClientId: '927459952659-53tuu1eckgf1ev15gmukjn8oolsppi6u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );
}
